### ISSUE TITLE
Windows: pip install leads to encoding error

### ISSUE THREAD

**Issue by SubhoBoy** [MangDL/MangDL#1]
Programmatic install of the application through pip leads to a `UnicodeDecodeError`, in `setup.py`, when it reads from README.md, as shown below:
`UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 11656: character maps to <undefined>`
After digging around a bit, I found that this is due to Windows interfering with the default `utf-8` encoding for Python, instead making it open with the `cp1252` encoding. There must be a character in the README that isn't a part of cp1252, so it throws an error when trying to handle it.** The fix is simple, just specify the encoding as `utf-8` in the `open()` function:
```
with open("docs/README.md", "r", encoding="utf-8") as f:
    ld = f.read()
```
\** These are just my random conclusions as a fellow amateur Python developer, don't take my word for it, I hardly understood what I wrote there myself.

Looking forward to actually getting to use your app!

**Comment by whinee** [comment]
Hello, will do! Although, since I do not own a Windows machine, would you be so kind to test it? Thank you so much!

**Comment by whinee** [comment]
Hello, the proposed change is now up and running in the pypi. Please test it. Thank you very much~

**Comment by SubhoBoy** [comment]
Yes, it does install successfully now, sorry for the delay in answering. 

However there still seem to be some Windows compatibility issues that render it not working. I'll open a new issue about it.
EDIT: I totally forgot about this, and one of the updates seems to have fixed it. It's functional now!
